#ifndef PinSetup_H
#define PinSetup_H

#include "e220.h"
#include "AltitudeManager.h"
#include "bno055.h"

#define BARO_I2C_SDA_PIN PC9
#define BARO_I2C_SCL_PIN PA8

#define IMU_I2C_SDA_PIN PB7
#define IMU_I2C_SCL_PIN PB6

#define RF_TX_PIN PE8
#define RF_RX_PIN PE7

#define RF_AUX_PIN PB2
#define RF_M0_PIN PE10
#define RF_M1_PIN PE9

#define GPS_TX_PIN PE1
#define GPS_RX_PIN PE0

#define DEBUG_TX_PIN PC6
#define DEBUG_RX_PIN PC7

#define RS232_TX_PIN PB10
#define RS232_RX_PIN PB11

#define PYRO_MAIN_PIN PE2
#define PYRO_APOGEE_PIN PE3

#define BUZZER_PIN PE12

#define CONFIG_RF_HIGH_ADDR 0x12
#define CONFIG_RF_LOW_ADDR 0x83

#define CONFIG_RF_CHANNEL FREQ_433
#define CONFIG_RF_BAUDRATE RF_UART_BAUD::UARTBAUDRATE_115200
#define CONFIG_RF_AIR_DATA_RATE RF_AIR_DATA::AIRDATARATE_48k
#define CONFIG_RF_RSSI_BYTE RF_ONOFF::RF_OFF
#define CONFIG_RF_PACKET_SIZE RF_PACKET_SIZE::PACKET_64
#define CONFIG_RF_TRANSFER_MODE RF_TRANS_MODE::FIXEDMODE
#define CONFIG_RF_TRANSFER_POWER RF_TRANS_POWER::TRANSMISSIONPOWER_30
#define CONFIG_RF_WIRELESS_WAKEUP RF_WIRELESS::WIRELESSWAKEUP_500
#define CONFIG_RF_UART_PARITY RF_UART_PARITY::UARTPARITY_8N1
#define CONFIG_RF_LBT_ENABLE RF_ONOFF::RF_OFF
#define CONFIG_RF_RSSI_AMBIENT RF_ONOFF::RF_OFF

#define CONFIG_BMP_PRESSURE_OVERSAMPLING BMP_Oversampling::BMP_OverSampling_4x
#define CONFIG_BMP_TEMPERATURE_OVERSAMPLING BMP_Oversampling::BMP_OverSampling_1x
#define CONFIG_BMP_IIR_SAMPLING BMP_IIR_Sampling::BMP_IIR_1X
#define CONFIG_BMP_ODR_SAMPLING BMP_ODR::BMP_ODR_40ms

#define CONFIG_LPS_ODR_RATE LPS_OUTPUT_DATA_RATE::LPS_OUTPUTDATARATE25HZ
#define CONFIG_LPS_LPFP LPS_EN_LPFP::LPS_LPFPENABLE
#define CONFIG_LPS_BDU LPS_BDU::LPS_BDU_CONT
#define CONFIG_LPS_LOW_NOISE LPS_LOWNOISE::LPS_LOW_NOISE

#define RF_SEND_HIGH_ADDR 0x19
#define RF_SEND_LOW_ADDR 0x23

#endif